    spring :
          profiles:
                active: dev

    spring :
        mvc:
          view :
            prefix : /templates/
            suffix : .html
        static-path-pattern : /resources/**

    spring:
        profiles: dev
    spring.datasource:
                   url: jdbc:mariadb://localhost:3306/CLOUD_APP
                   username: root
                   password: root
                   driver-class-name: org.mariadb.jdbc.Driver

    spring:
       profiles: test
    spring.datasource:
               url: jdbc:mariadb://localhost:3306/springboot
               username: root
               password: root
               driver-class-name: org.mariadb.jdbc.Driver

    spring:
          jpa:
              database-platform: org.hibernate.dialect.MariaDBDialect
              hibernate:
                ddl-auto: update
                generate-ddl: true
